#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 16 17:17:04 2020

@author: lh644
"""

import numpy as np
import matplotlib.pyplot as plt

a = np.load('cs-h-l1-s2_attempt_1.npz')
strain_mat = a['strain_mat']

applied_load=[0, 50, 100, 150, 200, 250, 300, 350, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950]
mean_strain=np.mean(strain_mat[:,:,11,0],axis=1)    
std_strain=np.std(strain_mat[:,:,11,0],axis=1)    
   
plt.errorbar(applied_load,mean_strain,std_strain)